### ISSUE TITLE
Permissions for POSTing actions: Limit POST to device owner only

### ISSUE THREAD

**Issue by forste** [eReuse/devicehub-teal#27]
Currently, any user can `POST` an `Action` for any device.

This should be limited to the owner, determined by the `owner_id` property, of the device

**Comment by fedjo** [comment]
Ok.
So far the ```owner_id``` is supported only from ```Computer``` devices and its subclasses (Laptop, Server, Desktop).

**Comment by fedjo** [comment]
I added a permission restriction for the current user if is not owner of the (non-component) device when performing a `Snapshot` action.

Implementation 4bbd53a

**Comment by fedjo** [comment]
Branch [feature/27-permission-posting-action](https://github.com/eReuse/devicehub-teal/tree/feature/27-permission-posting-action)

**Comment by forste** [comment]
has this been tested?

if yes and it worked, has the branch https://github.com/eReuse/devicehub-teal/tree/feature/27-permission-posting-action been merged into devel?

**Comment by JNadeu** [comment]
I was able to manually test (E2E) this feature. And the result was positive, since it can't upload a snapshot from another user. It returns me: 
_{"code":403,"message":"403 Forbidden: You don't have the permissions to access the requestedresource. It is either read-protected or not readable by theserver.","type":"InsufficientPermission"}_

@fedjo I think we could do the merge/pull request to testing branch now.
